### ISSUE TITLE
Does CKAN DataStore support non-ASCII characters?

### ISSUE THREAD

**Issue by jindrichmynarz** [OpenDataNode/UVPlugin-relationalToCKAN#11]
When I try to upload a RelationalDataUnit that contains non-ASCII characters, `UnicodeEncodeError` is raised. See https://gist.github.com/jindrichmynarz/3402f7db60010694a54b for complete details from the CKAN log (i.e. `/var/log/apache2/odn-ckan-ic.error.log`). It seems that CKAN fails on characters included in the values such as `NOTIFICATIONTYPE":"Informa\\xc4\\x8dn\\xc3\\xa9 ozn\\xc3\\xa1menie"`.

**Comment by mvi-eea-sk** [comment]
fixed in commit: https://github.com/OpenDataNode/odn-ckan/commit/feb1fa334fc10bd24a3ce3f1e776af10b0452715
so in ODNv_1.1.1 and newer it should be OK

**Comment by jindrichmynarz** [comment]
This issue seems to be fixed by the linked patch. Thanks!
